-- Sample AI Workspace Apps to test the new visual system

INSERT INTO ai_workspace_apps (name, description, status, category, app_type, folder_group, priority, github_url, vercel_url, live_url, business_value, target_user, is_internal_tool, is_sellable_product, created_at, updated_at)
VALUES 
(
  'ZeroOrigins OS',
  'Internal company operating system for managing projects, leads, and AI workspace experiments.',
  'deployed',
  'internal_tool',
  'web_app',
  'Live',
  'high',
  'https://github.com/iamnawin/zeroorigins-os',
  'https://zeroorigins-os.vercel.app',
  'https://os.zeroorigins.com',
  'Centralized command center for all ZeroOrigins operations, tracking, and automation.',
  'Internal ZeroOrigins team',
  true,
  false,
  NOW(),
  NOW()
),
(
  'PLOTDNA-AI',
  'AI-powered tool for generating complex data visualizations and analytical plots.',
  'in_progress',
  'ai_tool',
  'web_app',
  'Repos',
  'medium',
  'https://github.com/iamnawin/plotdna-ai',
  NULL,
  NULL,
  'Automated data visualization for researchers and analysts.',
  'Data scientists, researchers',
  false,
  true,
  NOW(),
  NOW()
),
(
  'Portfolio V3',
  'Personal portfolio website showcasing projects and skills.',
  'deployed',
  'website',
  'web_app',
  'Live',
  'low',
  'https://github.com/iamnawin/portfolio-v3',
  'https://portfolio-v3.vercel.app',
  'https://naveen.zeroorigins.com',
  'Professional presence and client acquisition.',
  'Potential clients, employers',
  false,
  false,
  NOW(),
  NOW()
),
(
  'Applyo Platform',
  'Job application tracking and management platform.',
  'active',
  'productivity_tool',
  'web_app',
  'Repos',
  'medium',
  'https://github.com/iamnawin/applyo-platform',
  NULL,
  NULL,
  'Streamlined job search and application management.',
  'Job seekers, career changers',
  false,
  true,
  NOW(),
  NOW()
),
(
  'ServiceOps Pulse',
  'Salesforce-integrated service operations monitoring dashboard.',
  'idea',
  'integration',
  'salesforce_app',
  'Ideas',
  'high',
  NULL,
  NULL,
  NULL,
  'Real-time service health monitoring for enterprise customers.',
  'Enterprise IT teams',
  false,
  true,
  NOW(),
  NOW()
);